### ISSUE TITLE
Compute background renderer content on demand?

### ISSUE THREAD

**Issue by Dirkster99** [siegfriedpammer/AvalonEditSamples#1]
Thanks for this sample its been very useful indeed. I was able to apply background coloring of a word in this project: https://github.com/Dirkster99/Aehnlich

to outline the delete and insert of characters per line which are necessary to transfer one line into the other.
The original approach from Bill Menees' WinForm app [Diff.Net](http://menees.com/) was to compute these insert/delete patterns on demand - whenever the user wants to view a new line since computing all lines at once would be the same as implementing an O(n^2) compared to what would otherwise be linear.

Even the on demand computation would make it O(n^2) but the user interface is more responsive that way and the work load is distributed over time as states here: [at about line 137 in DiffLineViewModel.cs](https://github.com/Dirkster99/Aehnlich/blob/master/source/Demos/AehnlichLibViewModels/ViewModels/LineInfo/DiffLineViewModel.cs).

So, I've been trying to do this with AvalonEdit but am not sure if this is the right/best way to approach the issue. The current solution is to compute and cache the missing lines whenever the user scrolls the view [at line 124 in Scrollviewer_ScrollChanged](https://github.com/Dirkster99/Aehnlich/blob/master/source/AehnlichViewLib/Controls/DiffControl.xaml.cs)...

and this event is even raised when the document is loaded initially. So, it does not seem to be too bad - it invokes a command, which in turn, invokes the [ViewPortChangedCommand in 207](https://github.com/Dirkster99/Aehnlich/blob/master/source/Demos/AehnlichLibViewModels/ViewModels/AppViewModel.cs) via binding.

Overall, the code is working albeit beinig still oversimplified since the computation is on the UI thread. The current issue I am having is that the initial background coloring right after loading a new diff is only partially visible - that is I can see the first part of the first line being background colored but color items in the second or later line are only available if I scroll down and backup - probably because the first initial computation is too late or takes too long and a re-draw can only be enforced by scrolling up and down. Refer to these 2 screenshots to better understand what I mean:

The coloring after the initial load:
![untitled](https://user-images.githubusercontent.com/2129700/53907673-f5158b00-404d-11e9-89e2-898a92a02bf4.png)

The coloring after scrolling down and back-up
![untitled1](https://user-images.githubusercontent.com/2129700/53907679-f8107b80-404d-11e9-998a-8c34f196bc83.png)

My question is whether you know a good on demand implementation for making sure the coloring can be computed on demand and is visible when done. Maybe you had to solve a similar problem in SharpDevelop?

I have played with the [Redraw() method](https://stackoverflow.com/questions/12033388/avalonedit-how-to-invalidate-line-transformers) before as can be seen in [this commit](https://github.com/Dirkster99/Aehnlich/commit/a917c9a7547f1b40dfb6ff7181ab21d51bde25fe), where I removed it since I found odd corner cases where the UI appeared to be locked when trying to resize the Window with the resize handle :-(

Would you be able to tell me a more promising and stable solution towards solving this issue?

**Comment by siegfriedpammer** [comment]
Calculating the diff inside the Draw method is a bad idea.

You should do that only once when the documents are loaded by your application. You could take some inspiration from the DefaultChangeWatcher implementation in SharpDevelop: https://github.com/icsharpcode/SharpDevelop/blob/master/src/AddIns/DisplayBindings/AvalonEdit.AddIn/Src/ChangeMarkerMargin/DefaultChangeWatcher.cs

One thing I noticed: https://github.com/Dirkster99/Aehnlich/blob/master/source/AehnlichViewLib/Controls/AvalonEditEx/DiffLineBackgroundRenderer.cs#L145 Why are you duplicating the brush for every part of every line? Seems to be a very inefficient thing.

Hope this helps!

**Comment by Dirkster99** [comment]
Hi Siegfried,

thanx for your hints - I did not fully understand the code you linked for SharpDevelop - partly because its not commented but mostly because the insides SharpDevelop are not trivial :-( but I got inspired and found a solution that works quit well :-)

I optimized the usage of brushs because I made sure the brush definitions in the XAML are frozen and then used as they are in the code (thanx for that hint).
[DiffLineBackgroundRenderer](https://github.com/Dirkster99/Aehnlich/blob/master/source/AehnlichViewLib/Controls/AvalonEditEx/DiffLineBackgroundRenderer.cs)

I ralized then, that whenever the rendering algorithm comes across a [non-computed line in the rendering](DiffLineBackgroundRenderer](https://github.com/Dirkster99/Aehnlich/blob/master/source/AehnlichViewLib/Controls/AvalonEditEx/DiffLineBackgroundRenderer.cs#L119) it shall be collected in list and be requested for computation via [LineDiffDataProvider interface](https://github.com/Dirkster99/Aehnlich/blob/master/source/AehnlichViewLib/Controls/AvalonEditEx/DiffLineBackgroundRenderer.cs#L129).

The code that lives behind that interface invokes a [non-ui thread](https://github.com/Dirkster99/Aehnlich/blob/master/source/Demos/AehnlichLibViewModels/ViewModels/DiffSideViewModel.cs#L245) which, when done, sends back an event, if and only if, there are any new diffs available for highlighting.

I am really happy with this solution because it appears smooth and I cannot see any flickers at all. I know the drawing is now executed twice for the highlighted elements but its still performing well even if there is a lot to highlight.

I guess the only improvement one could make here is to set out to compute lines earlier in the process. But that would have to be an event like OnStartRendering (before the actual call to Draw()) where it would already be clear what the beginning and end visual line is... I don't think there is an event like this...

What do you think about the solution? You can actually play with the demo because I added a suggestion box to reload other files via the refresh button - so I already looked at 2000 liners and the app freeze for a split sec because the loading and initial processing is still on the ui thread but other than that I think its really call :-)
